# Generated by Django 5.2.3 on 2025-06-11 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scamtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scamreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False)),
                ('evidence_text', models.TextField(blank=True, null=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence_files/')),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('name_or_number', models.CharField(help_text='Name or phone number of the Scammer', max_length=100)),
                ('social_media', models.CharField(help_text='Social media handle e.g  Discord, Telegram. Twitter(x),  etc', max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('scam_type', models.ManyToManyField(related_name='reports', to='Scam_reports.scamtype')),
            ],
        ),
    ]
