# Generated by Django 5.2.3 on 2025-07-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scam_reports', '0003_feedback'),
        ('Scam_reports', '0004_add_default_scamtypes'),
    ]

    operations = [
    ]
