# Generated by Codex on 2026-01-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scam_reports', '0005_merge_0003_feedback_0004_add_default_scamtypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
