# Generated by Codex on 2026-01-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scam_reports', '0006_remove_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreports',
            name='encounter_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scamreports',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportAbuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('personal_info', 'Contains personal information'), ('false_report', 'False or misleading report'), ('harassment', 'Harassment or hate speech'), ('other', 'Other')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='Scam_reports.scamreports')),
            ],
        ),
    ]
