# Generated by Codex on 2026-01-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scam_reports', '0007_trust_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreports',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scamreports',
            name='resolution_reason',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='ReportFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='Scam_reports.scamreports')),
            ],
        ),
    ]
