# Generated by Django 5.2.3 on 2026-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scam_reports", "0010_growth_ux"),
    ]

    operations = [
        migrations.AddField(
            model_name="digestsubscription",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="digestsubscription",
            name="verification_token",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="digestsubscription",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reportfollow",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reportfollow",
            name="verification_token",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="reportfollow",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="reportfollow",
            constraint=models.UniqueConstraint(
                fields=("report", "email"), name="unique_report_follow_email"
            ),
        ),
    ]
